listen_addresses = '*'
port = 5432
max_connections = 20

shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB
effective_cache_size = 256MB

timezone = 'UTC'
log_timezone = 'UTC'
password_encryption = 'scram-sha-256'

checkpoint_timeout = 10min
max_wal_size = 512MB
min_wal_size = 80MB
wal_compression = on

log_destination = 'stderr'
logging_collector = off
log_min_duration_statement = 1000
log_connections = off
log_disconnections = off
log_statement = 'none'
